name: Docker-Compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
